[build]
  command = "npm run build"  # Replace with your build command if necessary
  publish = "dist"  # Replace with the directory containing your built files

[functions]
  directory = "netlify/functions"